import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/commanComponents/NavBar/Navbar";
import { CardProvider } from "@/ContextAPI/CartContext";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CardProvider>
          <Navbar />
          <main>{children}</main>
          <ToastContainer position="bottom-center" autoClose={"2000"} />
        </CardProvider>
      </body>
    </html>
  );
}
